-- Criação do DataBase
CREATE DATABASE IF NOT EXISTS TRABALHO;
USE TRABALHO;
-- Criação da tabela ALUNO
CREATE TABLE ALUNO(
RA						INT NOT NULL,
NOME_ALUNO				VARCHAR(250) NOT NULL,
SEXO_ALUNO				CHAR(1) NOT NULL, -- F= Feminino-M= Masculino --
CONSTRAINT PK_RA PRIMARY KEY(RA)
);
-- Criação da tabela TURMA
CREATE TABLE TURMA(
NUM_TURMA				INT NOT NULL,
DTA_INICIO_AULAS		DATE NOT NULL,
DTA_FIM_AULAS			DATE NOT NULL,
CONSTRAINT PK_NUM_TURMA PRIMARY KEY(NUM_TURMA)
);
-- Criação da tabela MATRICULA
CREATE TABLE MATRICULA(
NUM_MATRICULA			INT NOT NULL,
DTA_MATRICULA			DATE NOT NULL,
DTA_CANCELAMENTO_MATRICULA	DATE,
RA						INT NOT NULL,
NUM_TURMA 				INT NOT NULL,
CONSTRAINT PK_NUM_MATRICULA PRIMARY KEY(NUM_MATRICULA),
CONSTRAINT FK_RA_MATRICULA
	FOREIGN KEY (RA) REFERENCES ALUNO(RA),
CONSTRAINT FK_NUM_TURMA_MATRICULA
	FOREIGN KEY (NUM_TURMA) REFERENCES TURMA(NUM_TURMA)
);
-- Criação da tabela DISCIPLINA
CREATE TABLE DISCIPLINA(
COD_DISCIPLINA				INT NOT NULL,
NOM_DISCIPLINA				VARCHAR(250) NOT NULL,
CARGA_HORARIA				INT NOT NULL,
CONSTRAINT PK_COD_DISCIPLINA PRIMARY KEY(COD_DISCIPLINA)
);
-- Criação da tabela PROFESSOR
CREATE TABLE PROFESSOR(
MATRICULA					INT NOT NULL,
NOME_PROFESSOR				VARCHAR(250) NOT NULL,
TITULACAO					VARCHAR(100) NOT NULL,
SEXO_PROFESSOR				CHAR(1) NOT NULL, -- F= Feminino-M= Masculino --
CONSTRAINT PK_MATRICULA PRIMARY KEY(MATRICULA)
);	
-- Criação da tabela DISCIPLINA_OFERECID
CREATE TABLE DISCIPLINA_OFERECIDA(
NUM_DISCIPLINA_OFERECIDA	INT NOT NULL,
SALA						VARCHAR(10) NOT NULL,
BLOCO						VARCHAR(10) NOT NULL,
DIA_SEMANA					INT NOT NULL, -- 1- Domingo/ 7- Sabado --
HOR_INICIO					TIME NOT NULL,
HOR_FIM						TIME NOT NULL,
MATRICULA					INT NOT NULL,
NUM_TURMA					INT NOT NULL,
COD_DISCIPLINA				INT NOT NULL,
CONSTRAINT PK_NUM_DISC_OFERECIDA PRIMARY KEY(NUM_DISCIPLINA_OFERECIDA),
CONSTRAINT FK_MATRICULA_DISC_OFERECIDA
	FOREIGN KEY (MATRICULA) REFERENCES PROFESSOR(MATRICULA),
CONSTRAINT FK_NUM_TURMA_DISC_OFERECIDA
	FOREIGN KEY (NUM_TURMA) REFERENCES TURMA(NUM_TURMA),
CONSTRAINT FK_COD_DISCIPLINA_DISC_OFERECIDA
	FOREIGN KEY (COD_DISCIPLINA) REFERENCES DISCIPLINA(COD_DISCIPLINA)
);
-- Criação da tabela AVALIACAO
CREATE TABLE AVALIACAO(
SEQ_AVALIACAO_ALUNO			INT NOT NULL,
NOTA_A2						DECIMAL(5,2) NOT NULL DEFAULT 0, -- A nota deve estar entre 0 e 5--
NOTA_A1						DECIMAL(5,2) NOT NULL DEFAULT 0, -- A nota deve estar entre 0 e 5--
NOTA_AF						DECIMAL(5,2) , -- A nota deve estar entre 0 e 5--
RA							INT NOT NULL,
NUM_DISCIPLINA_OFERECIDA	INT NOT NULL,
CONSTRAINT PK_SEQ_AVALIACAO_ALUNO PRIMARY KEY(SEQ_AVALIACAO_ALUNO),
CONSTRAINT FK_RA_AVALIACAO
	FOREIGN KEY (RA) REFERENCES ALUNO(RA),
CONSTRAINT FK_NUM_DISC_OFERECIDA_AVALIACAO
	FOREIGN KEY (NUM_DISCIPLINA_OFERECIDA) REFERENCES DISCIPLINA_OFERECIDA(NUM_DISCIPLINA_OFERECIDA)
);




    
    






















 
